version: "3.9"

services:
  # 1️⃣ เตรียมข้อมูลสำหรับ training/testing set
  prepare-data:
    build: .
    container_name: prepare-data
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    environment:
      - TEST_SET_PCT=20
    command: python prepare_data.py data/input data/output

  # 2️⃣ เทรนโมเดล
  training:
    build: .
    container_name: training-ml
    volumes:
      - ./data/output:/app/data/output
    environment:
      - N_ESTIMATORS=100
      - LEARNING_RATE=0.1
      - MAX_DEPTH=6
      - RANDOM_STATE=42
      - SCALE_POS_WEIGHT=12
    depends_on:
      - prepare-data
    command: python training-ml-xgboost.py data/output

  # 3️⃣ ทำนาย log ล่าสุดใน newdata/
  predict:
    build: .
    container_name: predict-ml
    volumes:
      - ./data/newdata:/app/data/newdata  
      - ./data/output:/app/data/output
    depends_on:
      - training
    environment:
      - TZ=Asia/Bangkok
    command: >
      python predict.py
      data/output/xgboost-model.pkl
      data/newdata
      data/output/classification_report_predict.html
