services:
  prepare-data:
    build: .
    container_name: prepare-data
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    environment:
      - TEST_SET_PCT=20
    command: python prepare-data.py data/input data/output

  training:
    build: .
    container_name: training-ml
    volumes:
      - ./data/output:/app/data/output
    environment:
      - N_ESTIMATORS=200
      - LEARNING_RATE=0.05
      - MAX_DEPTH=6
      - RANDOM_STATE=42
    depends_on:
      - prepare-data
    command: python training-ml-xgboost.py data/output
