services:
  prepare-data:
    build: .
    container_name: prepare-data
    working_dir: /app
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    environment:
      - TEST_SET_PCT=20
    command: python prepare_data.py data/input data/output

  training:
    build: .
    container_name: training-ml
    working_dir: /app
    volumes:
      - ./data/output:/app/data/output
    environment:
      - N_ESTIMATORS=100
      - LEARNING_RATE=0.1
      - MAX_DEPTH=6
      - RANDOM_STATE=42
      - SCALE_POS_WEIGHT=12
    depends_on:
      - prepare-data
    command: python training-ml-xgboost.py data/output

  predict:
    build: .
    container_name: predict-ml
    working_dir: /app
    volumes:
      - ./data/newdata:/app/data/newdata  
      - ./data/output:/app/data/output
    depends_on:
      - training
      - minio
    env_file:
      - environment_var.env
    command: >
      python predict.py
      data/output/xgboost-model.pkl
      data/newdata
      data/output/classification_report_predict.html

  minio:
    image: minio/minio
    container_name: minio-ml
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./data/minio:/data
    env_file:
      - environment_var.env
    command: server /data --console-address ":9090"

  dashboard:
    build: .
    container_name: dashboard-ml
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - ./data/output:/app/data/output
    depends_on:
      - predict
    command: streamlit run app_dashboard.py --server.port=8501 --server.address=0.0.0.0

  ml-serve:
    build: .
    container_name: ml-serve
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./data/output:/app/data/output
    depends_on:
      - training
    command: python ml-serve.py
